import Image from "next/image";
import Home from "@/components/Pages/Home";

export default function page() {
  return (
    <>
    <div className="min-h-screen bg-gradient-to-br from-[#EA502C] via-[#EA502C] to-[#EA502C] text-white p-6">
     <Home/>
     </div>
    </>
  );
}

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};
